// index.js
export const servicesData = [{
        title: "FullStack Development",
        description: "I build modern websites and web apps end-to-end — from UI/UX to backend and database. The focus is simple: clean architecture, fast performance, and a product that feels premium on every screen. Whether it’s a marketing site, dashboard, booking flow, or a custom web app, you get a build that’s reliable today and easy to evolve tomorrow.",
        items: [{
                title: "Backend Development",
                description: "(REST/GraphQL APIs, Microservices, Auth Systems)",
            },
            {
                title: "Frontend Excellence",
                description: "(React, Vue, TypeScript, Interactive UI/UX)",
            },
            {
                title: "Database Design",
                description: "(SQL/NoSQL Optimization, Scalable Structures)",
            },
        ],
    },
    {
        title: "UI/UX Design",
        description: "UI that looks premium and feels effortless. I design clear user flows, sharp layouts, and reusable component systems so your product stays consistent as you scale.",
        items: [{
                title: "User Flows & Wireframes",
                description: "(GitHub Actions, Docker, Kubernetes)",
            },
            {
                title: "High-Fidelity UI (Figma) ",
                description: "(Linux, Nginx, Load Balancing)",
            },
            {
                title: "Design Systems",
                description: "(Caching, Compression, Lighthouse 90+ Scores)",
            },
        ],
    },
    {
        title: "Platform Builds (WordPress / Framer / Wix)",
        description: "Need something fast, clean, and easy to manage? I build and customize WordPress, Framer, and Wix websites with the same attention to design and detail — so it doesn’t look platform made",
        items: [{
                title: "Website Setup & Customization",
                description: "(Refactoring, Tech Debt Cleanup)",
            },
            {
                title: "CMS Structure & Content Layout",
                description: "(Vulnerability Assessments)",
            },
            {
                title: "Launch, Fixes & Ongoing Updates",
                description: "(SSR, Metadata, Structured Data)",
            },
        ],
    },
    {
        title: "Visual / Graphic Design",
        description: "Design support for brands that need strong visuals across web and social. Clean, consistent assets that match your style — not random templates.",
        items: [{
                title: "Brand Visual Direction",
                description: "(Single codebase for iOS/Android/Web)",
            },
            {
                title: "Social Creatives & Ad Designs",
                description: "(Offline mode, Push Notifications)",
            },
            {
                title: "Web Graphics & Assets",
                description: "(Checkout flows, Payment Gateways, Inventory APIs)",
            },
        ],
    },
];
export const projects = [{
        id: 1,
        name: "Hubode Living",
        description: "Hubode Living is a brand-first website for a modern co-living concept built for “in-between” lives — interns, creators, coders, and young professionals. The site communicates Hubode’s mission and values with a calm, premium feel, while keeping the experience fast, responsive, and mobile-friendly.",
        href: "https://hubode-marketing-web.vercel.app/",
        image: "/assets/projects/hubode-living.png",
        bgImage: "/assets/backgrounds/blanket.jpg",
        frameworks: [
            { id: 1, name: "React" },
            { id: 2, name: "Next.js" },
            { id: 3, name: "Node.js" },
            { id: 3, name: "Docker" },
            { id: 3, name: "Sanity" },
            { id: 4, name: "MongoDB" },
            { id: 5, name: "Tailwind CSS" },
        ],
    },
    {
        id: 2,
        name: "PropertySeller UAE",
        description: "Designed the full UI/UX for PropertySeller UAE from scratch — a real-estate platform built to remove the usual chaos: duplicate listings, biased agents, and confusing steps. I worked closely with the team to shape the product flow, information architecture, and high-fidelity Figma prototype focused on clarity, trust, and an easy buying journey.",
        href: "https://www.propertyseller.com/",
        image: "/assets/projects/proeprty-seller.png",
        bgImage: "/assets/backgrounds/curtains.jpg",
        frameworks: [
            { id: 1, name: "UI/UX" },
            { id: 2, name: "Product Design" },
            { id: 2, name: "Figma" },
            { id: 2, name: "User Flows" },
            { id: 2, name: "Design System" },
        ],
    },
    {
        id: 3,
        name: "Combat Fitness Cult Wix",
        description: "Built the Combat Fitness Cult website on Wix with a custom UI/UX layer to match the brand’s high-intensity identity. Implemented Trials, Bookings, Memberships, and payment integration, plus structured pages for coaches, media, transformations, and online programs — designed to drive sign-ups and make the joining flow frictionless.",
        href: "https://www.cfcfit.com/",
        image: "/assets/projects/combat-fitness-cult.png",
        bgImage: "/assets/backgrounds/map.jpg",
        frameworks: [
            { id: 1, name: "Wix" },
            { id: 2, name: "Bookings" },
            { id: 3, name: "Memberships" },
            { id: 4, name: "Payments" },
            {
                id: 5,
                name: "Custom UI UX"
            },
        ],
    },
    {
        id: 4,
        name: "Künslerin",
        description: "Künslerin is a WordPress e-commerce website for an artist-led cosmetics brand focused on natural care, women empowerment, and community support. I worked on creating a clean, trust-building shopping experience that highlights the brand story, mission, and product values — while keeping the store flow simple from product discovery to checkout.",
        href: "https://kunstlerin.in/",
        image: "/assets/projects/kunstlerin.png",
        bgImage: "/assets/backgrounds/poster.jpg",
        frameworks: [
            { id: 1, name: "WordPress" },
            { id: 2, name: "WooCommerce" },
            { id: 3, name: "UI/UX" },
            { id: 4, name: "E-commerce" },
            { id: 5, name: "Responsive Design" },
        ],
    },
    {
        id: 5,
        name: "Find Fresh",
        description: "A premium UI/UX concept for Find Fresh — a fresh-juice and produce delivery brand focused on “made-on-demand” freshness. I designed the full customer journey in Figma, from browsing and product selection to ordering and checkout, with a clean visual style and a smooth, modern flow.",
        href: "https://www.figma.com/proto/4RkdodH6GTEKJ1awY3gZV9/Find-Fresh?page-id=0%3A1&node-id=1-2&viewport=-698%2C1301%2C0.64&t=ufnQo08k4D1zdDmX-1&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=1%3A2&show-proto-sidebar=1",
        image: "/assets/projects/findfresh.png",
        bgImage: "/assets/backgrounds/table.jpg",
        frameworks: [
            { id: 1, name: "UI/UX" },
            { id: 2, name: "Product Design" },
            { id: 3, name: "Figma" },
            { id: 4, name: "User Flows" },
            { id: 5, name: "High-Fidelity Prototype" },
        ],
    },
    {
        id: 6,
        name: "Gamca Medical",
        description: "A Next.js web app for GAMCA Medical Appointment with a full booking flow and Razorpay payment integration. Built to simplify GAMCA slip/medical test registration by guiding users step-by-step and handling confirmation securely through a Node.js backend.",
        href: "https://www.gamcakerala.com/",
        image: "/assets/projects/gamca-kerala.png",
        bgImage: "/assets/backgrounds/curtains.jpg",
        frameworks: [
            { id: 1, name: "Next.js" },
            { id: 2, name: "Node.js" },
            { id: 3, name: "MongoDB" },
            { id: 3, name: "Booking" },
            { id: 3, name: "Razorpay" },
            { id: 3, name: "SCSS" },
        ],
    },
    {
        id: 7,
        name: "Beyond Senses Architects",
        description: "Custom WordPress website for Beyond Senses Architects, built in close collaboration with founder Nabeel to match the studio’s tone and portfolio needs. The site focuses on strong storytelling, clean typography, and a smooth project browsing experience — designed to build trust and present their work like a premium brand.",
        href: "https://thebeyondsenses.com/",
        image: "/assets/projects/beyond-senses.png",
        bgImage: "/assets/backgrounds/curtains.jpg",
        frameworks: [
            { id: 1, name: "WordPress" },
            { id: 2, name: "Custom Design" },
            { id: 3, name: "UI/UX" },
            { id: 4, name: "Responsive" },
            { id: 5, name: "Portfolio CMS" },
        ],
    },
    {
        id: 7,
        name: "Emiraaz UAE",
        description: "Custom WordPress website for Beyond Senses Architects, built in close collaboration with founder Nabeel to match the studio’s tone and portfolio needs. The site focuses on strong storytelling, clean typography, and a smooth project browsing experience — designed to build trust and present their work like a premium brand.",
        href: "https://thebeyondsenses.com/",
        image: "/assets/projects/beyond-senses.png",
        bgImage: "/assets/backgrounds/curtains.jpg",
        frameworks: [
            { id: 1, name: "WordPress" },
            { id: 2, name: "Custom Design" },
            { id: 3, name: "UI/UX" },
            { id: 4, name: "Responsive" },
            { id: 5, name: "Portfolio CMS" },
        ],
    },
    {
        id: 9,
        name: "Berad",
        description: "Designed and built the Berad website as a high-performance Next.js experience with a custom Figma UI/UX and smooth GSAP animations. The site communicates Berad’s vision around sustainable, tech-enabled home essentials — using clean layouts, motion, and responsive design to make the brand feel premium and future-focused.",
        href: "https://berad.in/",
        image: "/assets/projects/berad.png",
        bgImage: "/assets/backgrounds/curtains.jpg",
        frameworks: [
            { id: 1, name: "Next.js" },
            { id: 2, name: "Figma" },
            { id: 3, name: "UI/UX" },
            { id: 4, name: "GSAP" },
            { id: 5, name: "SCSS" },
        ],
    },
];
export const socials = [
    { name: "Instagram", href: "https://www.instagram.com/fenarkhan/" },
    { name: "LinkedIn", href: "https://www.linkedin.com/in/fenarkhan/" },
    { name: "GitHub", href: "https://github.com/Fenar7" },
];